version: "3.7"

services:
  theme-db:
    container_name: koc-theme-db
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - koc-theme-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: theme
      MYSQL_DATABASE: theme

  theme:
    container_name: theme
    image: gradle:7.6.1-jdk17-focal
    ports:
      - 8082:8080
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "gradle bootRun"


volumes:
  koc-theme-data: