version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: local-mysql
    environment:
      - MYSQL_DATABASE=theme
      - MYSQL_ROOT_PASSWORD=1234!
      - TZ=Asia/Seoul
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - local-mysql:/var/lib/mysql
    networks:
      - yas-net
  app:
    container_name: spring-app
    image: openjdk:11-jdk
    ports:
      - “8082:8082”
    volumes:
      - ./app:/app
    working_dir: /app
    command: [ “./gradlew”, “bootrun” ]
    depends_on:
      - db
    restart: always
volumes:
  local-mysql:
