server:

app:
  host: http://localhost:8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://koc-theme-db:3306/theme?serverTimezone=Asia/Seoul
    username: root
    password: theme
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

springdoc:
  version: '1.0.0'
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: method

sql:
  init:
    platporm: mysql
    data-locations: classpath:data.sql
