server:


spring:
  jpa:
    generate-ddl: 'false'
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
        format_sql: 'true'
    database: mysql
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create


springdoc:
  version: '1.0.0'
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: method

app:
  host: http://localhost:8082
  title: Devellany's sample
  version: ver.prototype
  help-email: #MAIL_SENDER_ADDRESS
  token-available-period: 60